//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reyes_MidtermExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesDetail
    {
        public int SalesDetail_Id { get; set; }
        public int Sale_Id { get; set; }
        public int Product_Id { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
